server:
  port: 8888
  tomcat:
    connection-timeout: 5s
    keep-alive-timeout: 30s
    threads:
      max: 50
      min-spare: 5
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sarath-ps/catalog-service-config-repo.git
          default-label: main
          clone-on-start: true
          force-pull: true